### ISSUE TITLE
Modified CSS with panel in lower half, allowing DSK use in ATEM mini

### ISSUE THREAD

**Issue by RaimundE** [aaronpk/youtube-chat-overlay#3]
We hacked the CSS to swap the list of questions up and the black pane down on the page. That allows us to broadcast the overlay through the Mini's DSK where we can mask top and bottom, but not position. The precious USK stays available for our Chroma keying.
[Youtube-Chat-CSS-inverted.txt](https://github.com/aaronpk/youtube-chat-overlay/files/4659219/Youtube-Chat-CSS-inverted.txt)

**Comment by aaronpk** [comment]
Thanks, I've done something similar in the project now!
